@apiUrl = http://localhost:3030/boards   
@token = {{$dotenv TOKEN}}




GET 
Authorization: Bearer {{token}}
###

POST {{apiUrl}}
Content-Type: application/json

{
  "name": "My New Board",
  "userId": "dasd" 
}

###

POST {{apiUrl}}
Content-Type: application/json

{
  "board": "xd",
  "createdBy": "test"
}