@apiUrl = http://localhost:3030/board   



GET {{apiUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE1Y2JkNTAyMzdkMjA1ODI5MWEzYjMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInVzZXJuYW1lIjoiQWRtaW4iLCJyb2xlcyI6WyJEZXYiLCJBZG1pbiJdLCJib2FyZHMiOlsiNjUxNWM5NzE1YzQ5MWFkZjRmM2IyMTE1IiwiNjUxNWNhMDU1YzQ5MWFkZjRmM2IyMTE2IiwiNjUxNWNhMTE1YzQ5MWFkZjRmM2IyMTE3IiwiNjUxNWNhMTk1YzQ5MWFkZjRmM2IyMTE4Il0sImV4cGlyZXNJbiI6IjFkIiwiaWF0IjoxNjk1OTI3NTgwfQ.VYaF0RD_GwwjGWxV00mOVthD9h5sLFsioS4odmp2wIs

###
//kom ihåg att ta en ny jwt token från en inloggad user innan du skapar en board?!
POST {{apiUrl}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE1Y2JkNTAyMzdkMjA1ODI5MWEzYjMiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInVzZXJuYW1lIjoiQWRtaW4iLCJyb2xlcyI6WyJEZXYiLCJBZG1pbiJdLCJib2FyZHMiOlsiNjUxNWM5NzE1YzQ5MWFkZjRmM2IyMTE1IiwiNjUxNWNhMDU1YzQ5MWFkZjRmM2IyMTE2IiwiNjUxNWNhMTE1YzQ5MWFkZjRmM2IyMTE3IiwiNjUxNWNhMTk1YzQ5MWFkZjRmM2IyMTE4Il0sImV4cGlyZXNJbiI6IjFkIiwiaWF0IjoxNjk1OTI3NTgwfQ.VYaF0RD_GwwjGWxV00mOVthD9h5sLFsioS4odmp2wIs
Content-Type: application/json

{
  "board": "RestingTesting"
}