@apiUrl = http://localhost:3030/users   
@token = {{$dotenv TOKEN}}

//board IDs - kan skapas mera boards vid behov men dessa för att kunna lägga till olika användare
//roles onödiga för tillfället eftersom vi lägger boards rakt in till användaren
@projektplanering = 6515c9715c491adf4f3b2115
@brainstorming = 6515ca055c491adf4f3b2116

@Allmänt = 6515ca235c491adf4f3b2119

@socials = 6515ca195c491adf4f3b2118
###
GET {{apiUrl}}
Authorization: Bearer {{token}}
###
GET {{apiUrl}}/6512c8233a0c3364900557a3
Authorization: Bearer {{token}}

### Logga in på /users/login
POST {{apiUrl}}/login
Content-Type: application/json

{
    "email": "jake@jake.com",
    "password": "test"
}

### skapa ny användare
POST {{apiUrl}}
Content-Type: application/json

{
    "username": "banana",
    "email": "banana@banana.com",
    "password": "banana",
    "roles": ["banana", "fruit"],
    "boards": ["{{projektplanering}}", "{{brainstorming}}","{{Allmänt}}","{{socials}}"]
}

### 
PATCH {{apiUrl}}/64f9a89c3192a9bf9d0e740a
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "password": "Password123"
}

###
DELETE {{apiUrl}}/64f9aa07539b7df1d8de2397
Authorization: Bearer {{token}}

###